import { formatCurrency } from "../../utils/formatters";
import { TrendingUp, TrendingDown } from "lucide-react";

/**
 * TopProducts Component
 *
 * Displays a list of top-selling products in a card layout.
 * Each product shows its image, name, number of sales, revenue, and trend indicator.
 *
 * Props:
 * @param {Object[]} products - Array of product objects to display.
 * @param {string|number} products[].id - Unique identifier for the product.
 * @param {string} products[].name - Name of the product.
 * @param {string} products[].image - URL of the product image.
 * @param {number} products[].sales - Number of sales for the product.
 * @param {number} products[].revenue - Revenue generated by the product.
 * @param {'up'|'down'} products[].trend - Indicates whether the product's sales trend is up or down.
 *
 * Usage Example:
 * <TopProducts
 *   products={[
 *     { id: 1, name: "Product A", image: "/img/a.jpg", sales: 120, revenue: 5000, trend: "up" },
 *     { id: 2, name: "Product B", image: "/img/b.jpg", sales: 90, revenue: 3200, trend: "down" },
 *   ]}
 * />
 */
const TopProducts = ({ products = [] }) => {
  return (
    <div className="bg-white rounded-lg shadow-card">
      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-200">
        <h3 className="text-lg font-semibold text-gray-900">Top Products</h3>
      </div>

      {/* Product List */}
      <div className="p-6">
        <div className="space-y-4">
          {products.map((product) => (
            <div key={product.id} className="flex items-center gap-4">
              {/* Product Image */}
              <img
                src={product.image}
                alt={product.name}
                className="w-12 h-12 rounded-lg object-cover"
              />

              {/* Product Info */}
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-gray-900 truncate">
                  {product.name}
                </p>
                <p className="text-xs text-gray-500">{product.sales} sales</p>
              </div>

              {/* Revenue and Trend */}
              <div className="text-right">
                <p className="text-sm font-semibold text-gray-900">
                  {formatCurrency(product.revenue)}
                </p>
                <div className="flex items-center justify-end gap-1">
                  {product.trend === "up" ? (
                    <TrendingUp size={14} className="text-green-500" />
                  ) : (
                    <TrendingDown size={14} className="text-red-500" />
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default TopProducts;
